"""Bundle copies must be the catalogue, byte for byte.

A plugin manifest cannot reference anything outside its own root, and cross-
directory symlinks are skipped on local-path and `--plugin-dir` installs — so a
capability shared by two bundles travels as a real COPY, generated by
`harness/sync_bundles.py` (see its docstring for the full reasoning).

Copies buy correctness at every install path and pay for it with one hazard: an
edit made to a bundle copy instead of the catalogue is silently destroyed by the
next sync. This module is what makes that hazard loud. Upstream
(`aws/agent-toolkit-for-aws`) relies on CI for the same guard; this repo has none,
so these tests are the only thing standing between a hand-edited copy and a lost
change.

The always-run half needs nothing but the checkout. The positive controls operate
on a throwaway `copytree` clone, so they prove `--check` is FALSIFIABLE — a drift
guard that cannot fail is not a guard, the same standard `test_validator_negative`
holds the offline validator to.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

BET_ROOT = Path(__file__).resolve().parents[2]
PLUGINS_DIR = BET_ROOT / "plugins"
SCRIPT = BET_ROOT / "harness" / "sync_bundles.py"

sys.path.insert(0, str(BET_ROOT / "harness"))
from sync_bundles import (  # noqa: E402
    HOOK_ENTRY,
    KINDS,
    bundles,
    catalogue_index,
    entries_match,
    subscriptions,
)

BUNDLES = [p.name for p in bundles()]
KIND_NAMES = sorted(KINDS)


def _run(*args: str, cwd: Path = BET_ROOT) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(cwd / "harness" / "sync_bundles.py"), *args],
        cwd=cwd, capture_output=True, text=True, check=False,
    )


# ---------------------------------------------------------------------------
# Always runs against the real checkout.
# ---------------------------------------------------------------------------


def test_repo_is_in_sync_with_the_catalogue():
    """Shells out rather than calling `sync_bundle()` directly, so the CLI — the
    thing a maintainer and the bundle-plugin skill actually invoke — is under test,
    exit code included."""
    proc = _run("--check")
    assert proc.returncode == 0, (
        f"bundles have drifted from the catalogue:\n{proc.stderr}\n{proc.stdout}"
    )


def test_check_writes_nothing():
    """`--check` is used in the middle of a test run and by the skill's Step 1; if
    it mutated the tree it would mask the very drift it reports."""
    before = {
        p: p.stat().st_mtime_ns
        for p in PLUGINS_DIR.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }
    _run("--check")
    after = {
        p: p.stat().st_mtime_ns
        for p in PLUGINS_DIR.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }
    assert before == after


@pytest.mark.parametrize("bundle_name", BUNDLES)
@pytest.mark.parametrize("kind_name", KIND_NAMES)
def test_every_subscription_matches_its_catalogue_entry(bundle_name, kind_name):
    kind = KINDS[kind_name]
    index = catalogue_index(kind)
    bundle = PLUGINS_DIR / bundle_name
    for name in subscriptions(bundle, kind, index):
        assert entries_match(index[name], kind.entry_path(bundle, name)), (
            f"{bundle_name}/{kind_name}/{name} differs from plugins/{kind_name}/{name} "
            f"— edit the catalogue copy, then run `python3 harness/sync_bundles.py`"
        )


@pytest.mark.parametrize("bundle_name", BUNDLES)
@pytest.mark.parametrize("kind_name", KIND_NAMES)
def test_no_orphaned_entries(bundle_name, kind_name):
    """Every entry in a bundle either matches a catalogue name or is deliberately
    bundle-private. Today the repo has no bundle-private capabilities, so an
    unmatched entry means a catalogue entry was deleted or renamed out from under
    a subscriber — which `--check` cannot see, because an entry with no catalogue
    match is left alone by design."""
    kind = KINDS[kind_name]
    root = PLUGINS_DIR / bundle_name / kind_name
    if not root.is_dir():
        return
    index = catalogue_index(kind)
    present = {
        kind.entry_name(p)
        for p in root.iterdir()
        if (p.is_dir() if kind.is_dir else p.name.endswith(kind.suffix))
    }
    assert not (present - set(index)), (
        f"{bundle_name}/{kind_name} has entries with no catalogue source: "
        f"{sorted(present - set(index))}"
    )


@pytest.mark.parametrize("bundle_name", BUNDLES)
def test_manifest_hooks_array_matches_subscriptions(bundle_name):
    """Only `hooks/hooks.json` is auto-discovered — there is no `hooks/*.json`
    scan — so a copied hook that is not listed in `plugin.json` is inert, and a
    listed one that is not copied is a dangling path. Both fail silently at
    runtime, which is why this is asserted rather than trusted."""
    bundle = PLUGINS_DIR / bundle_name
    manifest = json.loads((bundle / ".claude-plugin/plugin.json").read_text())
    declared = manifest.get("hooks", [])
    if not isinstance(declared, list):
        pytest.skip(f"{bundle_name} uses the inline-object hooks form")

    index = catalogue_index(KINDS["hooks"])
    expected = {HOOK_ENTRY.format(name=n) for n in subscriptions(bundle, KINDS["hooks"], index)}
    ours = {e for e in declared if e in {HOOK_ENTRY.format(name=n) for n in index}}
    assert ours == expected, (
        f"{bundle_name} declares catalogue hooks {sorted(ours)} but subscribes to "
        f"{sorted(expected)}"
    )
    for entry in declared:
        assert entry.startswith("./"), (
            f"{bundle_name} hooks entry {entry!r} must be plugin-root relative and "
            "start with './' — the manifest schema rejects anything else"
        )
        assert (bundle / entry).is_file(), f"{bundle_name} hooks entry {entry!r} does not resolve"


@pytest.mark.parametrize("kind_name", KIND_NAMES)
def test_catalogue_is_not_mistaken_for_a_bundle(kind_name):
    root = PLUGINS_DIR / kind_name
    assert root.is_dir(), f"plugins/{kind_name}/ is missing — the catalogue kinds are fixed"
    assert not (root / ".claude-plugin/plugin.json").exists(), (
        f"plugins/{kind_name}/ must not carry a plugin manifest — every bundle "
        "enumeration in this suite identifies bundles by manifest presence, so a "
        "manifest here would make the catalogue a fourth plugin"
    )
    assert (root / "README.md").is_file(), (
        f"plugins/{kind_name}/README.md documents the per-kind runtime mechanics, "
        "and is also what lets git track the directory while it is empty"
    )


def test_no_symlinks_under_plugins():
    """Copies, deliberately, not links: cross-directory symlinks are dereferenced
    only by a marketplace install that git-clones the repo. Per the plugin
    reference, "for plugins installed with `--plugin-dir` or from a local path,
    only symlinks that resolve within the plugin's own directory are preserved.
    All others are skipped." A link that crept back in would silently ship a
    bundle with a missing capability."""
    links = [p.relative_to(BET_ROOT) for p in PLUGINS_DIR.rglob("*") if p.is_symlink()]
    assert not links, f"symlinks under plugins/: {links}"


# ---------------------------------------------------------------------------
# Positive controls — prove `--check` can actually fail.
# ---------------------------------------------------------------------------


@pytest.fixture()
def clone(tmp_path):
    """A throwaway copy of the repo tree the script reads: plugins/ + harness/."""
    dest = tmp_path / "repo"
    (dest / "harness").mkdir(parents=True)
    shutil.copy2(SCRIPT, dest / "harness" / "sync_bundles.py")
    shutil.copytree(
        PLUGINS_DIR, dest / "plugins",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    assert _run("--check", cwd=dest).returncode == 0, "clone should start in sync"
    return dest


def test_check_catches_a_mutated_bundle_copy(clone):
    copy = clone / "plugins/admin/skills/write-evals/SKILL.md"
    copy.write_text(copy.read_text(encoding="utf-8") + "\ntampered\n", encoding="utf-8")

    proc = _run("--check", cwd=clone)
    assert proc.returncode == 1
    assert "admin: skills/write-evals" in proc.stderr
    # The remediation must name the CATALOGUE, not the copy — pointing a
    # maintainer at the file that is about to be overwritten is worse than silence.
    assert "plugins/skills/write-evals" in proc.stderr


def test_check_catches_a_missing_file_in_a_bundle_copy(clone):
    (clone / "plugins/builder/skills/deploy-agent/assets/engine.py").unlink()
    assert _run("--check", cwd=clone).returncode == 1


def test_check_catches_an_extra_file_in_a_bundle_copy(clone):
    (clone / "plugins/builder/skills/write-evals/EXTRA.md").write_text("x", encoding="utf-8")
    assert _run("--check", cwd=clone).returncode == 1


def test_sync_repairs_every_mutation(clone):
    copy = clone / "plugins/admin/skills/write-evals/SKILL.md"
    copy.write_text("tampered", encoding="utf-8")
    (clone / "plugins/builder/skills/write-evals/EXTRA.md").write_text("x", encoding="utf-8")

    assert _run(cwd=clone).returncode == 0
    assert _run("--check", cwd=clone).returncode == 0
    assert copy.read_text(encoding="utf-8") == (
        clone / "plugins/skills/write-evals/SKILL.md"
    ).read_text(encoding="utf-8")
    assert not (clone / "plugins/builder/skills/write-evals/EXTRA.md").exists()


def test_hooks_round_trip_generates_and_removes_the_manifest_entry(clone):
    """The hooks path ships before any real hook exists, so it gets a synthetic
    one here rather than going out unexercised."""
    entry = clone / "plugins/hooks/demo-guard"
    entry.mkdir(parents=True)
    (entry / "hooks.json").write_text(
        json.dumps({
            "description": "demo",
            "hooks": {"PreToolUse": [{"matcher": "Bash", "hooks": [
                {"type": "command",
                 "command": 'bash "${CLAUDE_PLUGIN_ROOT}/hooks/demo-guard/check.sh"'},
            ]}]},
        }, indent=2) + "\n",
        encoding="utf-8",
    )
    (entry / "check.sh").write_text("#!/bin/bash\nexit 0\n", encoding="utf-8")

    manifest = clone / "plugins/builder/.claude-plugin/plugin.json"
    before = json.loads(manifest.read_text())
    assert "hooks" not in before

    assert _run("--add", "builder", "hooks", "demo-guard", cwd=clone).returncode == 0
    after = json.loads(manifest.read_text())
    assert after["hooks"] == ["./hooks/demo-guard/hooks.json"]
    assert (clone / "plugins/builder/hooks/demo-guard/check.sh").is_file()
    # Everything else in the manifest survives the rewrite.
    assert {k: v for k, v in after.items() if k != "hooks"} == before
    assert _run("--check", cwd=clone).returncode == 0

    assert _run("--remove", "builder", "hooks", "demo-guard", cwd=clone).returncode == 0
    assert json.loads(manifest.read_text()) == before
    assert not (clone / "plugins/builder/hooks").exists()


def test_check_catches_a_hand_edited_hooks_array(clone):
    manifest = clone / "plugins/hooks/demo/hooks.json"
    manifest.parent.mkdir(parents=True)
    manifest.write_text(json.dumps({"hooks": {}}) + "\n", encoding="utf-8")
    assert _run("--add", "admin", "hooks", "demo", cwd=clone).returncode == 0

    plugin_json = clone / "plugins/admin/.claude-plugin/plugin.json"
    doc = json.loads(plugin_json.read_text())
    doc["hooks"] = []  # a maintainer "cleaning up" the generated array
    plugin_json.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    proc = _run("--check", cwd=clone)
    assert proc.returncode == 1
    assert "`hooks` array" in proc.stderr


def test_add_rejects_unknown_bundle_kind_and_entry(clone):
    for args in (
        ("--add", "nope", "skills", "write-evals"),
        ("--add", "admin", "widgets", "write-evals"),
        ("--add", "admin", "skills", "no-such-skill"),
    ):
        proc = _run(*args, cwd=clone)
        assert proc.returncode == 2, f"{args} should be an operator error, got {proc.returncode}"
        assert "ERROR" in proc.stderr


def test_add_is_idempotent_and_remove_is_reversible(clone):
    assert _run("--add", "observer", "skills", "write-evals", cwd=clone).returncode == 0
    assert (clone / "plugins/observer/skills/write-evals/SKILL.md").is_file()

    proc = _run("--add", "observer", "skills", "write-evals", cwd=clone)
    assert proc.returncode == 0 and "already subscribes" in proc.stdout

    assert _run("--remove", "observer", "skills", "write-evals", cwd=clone).returncode == 0
    assert not (clone / "plugins/observer/skills").exists()
    assert _run("--check", cwd=clone).returncode == 0


def test_bundle_private_entries_are_left_alone(clone):
    """An entry with no catalogue match is legitimate and must survive a sync
    untouched — otherwise a bundle could never carry anything of its own."""
    private = clone / "plugins/observer/skills/observer-only"
    private.mkdir(parents=True)
    (private / "SKILL.md").write_text(
        "---\nname: observer-only\ndescription: private.\n---\nbody\n", encoding="utf-8"
    )
    assert _run(cwd=clone).returncode == 0
    assert (private / "SKILL.md").read_text(encoding="utf-8").endswith("body\n")
    assert _run("--check", cwd=clone).returncode == 0
